### ISSUE TITLE
which font

### ISSUE THREAD

**Issue by muayyad-alsadi** [ojuba-org/othman#22]
here we see
https://github.com/ojuba-org/othman/blame/master/othman/gtkUi.py

```
# 2012: port to gtk3  by Ehab
        self.cells[0].set_property("font", "Simplified Naskh 32")
```

but here

https://github.com/ojuba-org/othman/blame/09eeebd205666b42764f372d907aede38994efb1/othman/gtkUi.py

```
# أحمد المحمودي (Ahmed El-Mahmoudy) committed on Apr 2, 2014

        self.cells[0].set_property("font", "Amiri Quran 24")
```

so despite 2014 being more recent, I can't see it in history

**Comment by muayyad-alsadi** [comment]
@moceap @ehabsas @aelmahmoudy  I'm packing it for flathub and the font is broken, because it ships Amiri while the code references Simplified

**Comment by muayyad-alsadi** [comment]
should I use your repo ?

https://github.com/aelmahmoudy/othman/blob/master/othman/gtkUi.py#L200

**Comment by aelmahmoudy** [comment]
On Mon, Sep 23, 2019 at 06:21:14AM -0700, Muayyad Alsadi wrote:
> should I use your repo ?
> https://github.com/aelmahmoudy/othman/blob/master/othman/gtkUi.py#L200
---end quoted text---

I would recommend using Amiri font

-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by muayyad-alsadi** [comment]
would you please create a branch called "amiri" based on latest master on your fork

* gtkUi.py reference amiri
* text that is suitable for amiri font

**Comment by muayyad-alsadi** [comment]
@aelmahmoudy please be a maintainer on flathub with us here

https://github.com/flathub/com.github.ojubaorg.Othman

**Comment by muayyad-alsadi** [comment]
@aelmahmoudy  your branch uses bitbucket url which does not seem to be working

https://bitbucket.org/khaledhosny/quran.git

maybe should be replaced with this

https://github.com/khaledhosny/quran-data

**Comment by aelmahmoudy** [comment]
Done, please test as I cannot test currently

-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by muayyad-alsadi** [comment]
I'll handle it

**Comment by mustafa0x** [comment]
Consider using Kitab font (see e.g. furqan.co) + the Qur'an text I've worked on: https://github.com/alquran-foundation/quran-text.

**Comment by xlmnxp** [comment]
الافضل استخدام هذا الخط حر وخط عثماني للقران الكريم
https://fonts.qurancomplex.gov.sa/wp02/%d8%ae%d8%b7-%d9%82%d8%a7%d9%84%d9%88%d9%86
