### ISSUE TITLE
البرنامج لا يعمل على أوبونتو أو دبيان

### ISSUE THREAD

**Issue by mhsabbagh** [ojuba-org/othman#33]
يظهر الخطأ التالي على التوزيعات الدبيانية عند محاولة تشغيل البرنامج بعد تثبيته من المصادر الرسمية:

```
mhsabbagh@pop-os:~$ sudo apt install othman-browser
mhsabbagh@pop-os:~$ othman-browser
/usr/lib/python3/dist-packages/othman/gtkUi.py:23: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, Pango, GdkPixbuf
Traceback (most recent call last):
  File "/usr/bin/othman-browser", line 4, in <module>
    main()
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 425, in main
    w = othmanUi()
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 115, in __init__
    self.connect("delete_event", self.quit)
TypeError: <gtkUi.othmanUi object at 0x7f44aedf1940 (othman+gtkUi+othmanUi at 0x55cab9d86310)>: unknown signal name: delete_event
```

حتى عند إصلاح المشكلة (ببساطة عبر إزالة السطر 115 من الشفرة المصدرية فهو غير ضروري)، تظهر مشكلة أخرى مثل:

```
mhsabbagh@pop-os:~$ othman-browser
/usr/lib/python3/dist-packages/othman/gtkUi.py:23: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, Pango, GdkPixbuf
Traceback (most recent call last):
  File "/usr/bin/othman-browser", line 4, in <module>
    main()
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 424, in main
    w = othmanUi()
  File "/usr/lib/python3/dist-packages/othman/gtkUi.py", line 118, in __init__
    self.clip1 = Gtk.Clipboard.get(Gdk.SELECTION_PRIMARY)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Clipboard'
```

الإصدار 0.6.0-2.

يا ترى هل هي مشكلة متعلقة بالحزمة الدبيانية (هل يحتاجون جلب إصدار أحدث) أم أيضًا على توزيعات أخرى؟

**Comment by ali-sameh-galal** [comment]
ـ @mhsabbagh الحزمة الدبيانية مبنية على إصدار ``0.6.0`` من مصحف عثمان والكود الخاص بهذا الإصدار قديم جدا، بالعودة الى الكود الخاص بهذا الإصدار وعمل ``import`` للـ ``gi`` ومن ثم تحديد رقم إصدار مكتبة ``GTK`` الى ``Gtk 3.0``سيعمل البرنامج بدون مشاكل كما في الصورة حاليا التطبيق يحتاج شخص لعمل تحزيم جديد للبرنامج باستخدام الكود الحالي الموجود في المستودع لأنه يعمل بدون أي مشاكل.

![Screenshot from 2023-01-10 23-32-01](https://user-images.githubusercontent.com/66528793/211669107-95da53d4-706a-4303-9887-1feb089145f6.png)

**Comment by mhsabbagh** [comment]
تمام إذًا المشكلة بالتحزيم. سأفتح علّة عند مشروع دبيان لطلب تحزيم البرنامج بالإصدار الأخير ثم سأحدّث هذه الصفحة هنا.

حزم أوبونتو قادمة من دبيان ولذلك ستصل تدريجيًا إلى أوبونتو.

**Comment by mhsabbagh** [comment]
هناك أمر لاحظتُه هنا، هو أن البرنامج يعمل على دبيان 11 رغم أنه نفس الإصدار (اختبرتُه بنفسي)، بينما لا يعمل على أوبونتو وما بني عليها.

السبب أن البرنامج بإصداره المحزّم لا يحدد إصدار Gtk المطلوب، فيستورد المكتبة الموجودة بآخر إصدار (GTK 4 في حالة أوبونتو 22.04)، لكن هذا يعني أن المشكلة منحصرة في أوبونتو وقد بلغتُ عنها هناك: https://bugs.launchpad.net/ubuntu/+source/othman/+bug/2002865

لكن هذا كان ليعني أن دبيان ستعاني من نفس المشكلة إن انتقلت إلى استخدام إصدار أحدث من Gtk وجنوم مستقبلًا.

**Comment by mhsabbagh** [comment]
الحمد لله اكتمل إصلاح العلّة على أوبونتو (ولعله يُنقل إلى دبيان لاحقًا) عبر ترقيع بسيط وفّرته للحزمة: https://bugs.launchpad.net/ubuntu/+source/othman/+bug/2002865

ستحتاج الحزمة وقتًا إلى أن تصل المستودعات الرسمية لأوبونتو 22.04 و22.10، لكنها ستصل إن شاء الله.

تحياتي.
